title: Daoud Piracha. Projects website and Blog
email: daoud.piracha@mail.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  I solve problems in Data Science and AI.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Daoud Piracha # add your name
author-pic: daoud-face2.jpg
about-author: Hi there, my name is Daoud. I study patterns in data and irrational behaviour in general. I also like biking, coffee and AI. #Currently, I am building Attention submodules for VGG for the ICLR 2018 Reproducibility Challenge.

# Contact links
email: daoud.piracha@mail.mcgill.ca # Add your Email address
phone: 111111111 # Add your Phone number
website: daoudpiracha.me # Add your website, do not add http://
linkedin: daoud-piracha-224249127 # Add your Linkedin handle
github: DaoudPiracha # Add your Github handle
twitter:  partiallyd # Add your Twitter handle
facebook: daoud.piracha # Add your Facebook handle
instagram: daoud.piracha # Add your Instagram handle
pinterest: random # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
